name: Deploy to Azure AKS

on:
  push:
    branches: [ main ]

env:
  DOCKERHUB_REPOSITORY: abhithind31/wordpress
  AKS_RESOURCE_GROUP: experimentation
  AKS_CLUSTER_NAME: Delhivery

jobs:
  build:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
    - name: Set short git commit SHA
      id: commit
      uses: prompt/actions-commit-hash@v2

    - name: Check out code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build, tag, and push image to Docker Hub
      env:
        IMAGE_TAG: ${{ steps.commit.outputs.short }}
      run: |
        docker build -t $DOCKERHUB_REPOSITORY:$IMAGE_TAG .
        docker push $DOCKERHUB_REPOSITORY:$IMAGE_TAG

    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up AKS credentials
      run: az aks get-credentials --resource-group $AKS_RESOURCE_GROUP --name $AKS_CLUSTER_NAME --overwrite-existing

    - name: Update Deployment Image
      env:
        IMAGE_TAG: ${{ steps.commit.outputs.short }}
      run: |
        kubectl set image deployment/flask-app flask-app=$DOCKERHUB_REPOSITORY:$IMAGE_TAG
